# Setup
title:               Sam O'Nuallain
tagline:             ''
description:         'Computer science and economics student @ UMass Amherst'
url:                 https://samonuall.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sam O'Nuallain
  url:               https://www.linkedin.com/in/sam-o-nuallain-4972791b9/
  email:             samonuall@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
